services:
  db:
    image: postgres:15-alpine
    container_name: pzsmp_db
    environment:
      POSTGRES_DB: pzsmp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./pzsmp
    container_name: pzsmp_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pzsmp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "12345"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
          condition: service_healthy
    restart: on-failure

  frontend:
    build: ./pzsmp-frontend
    container_name: pzsmp_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  pgdata: